import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const js = readFileSync(new URL('../../static/js/canvas.js', import.meta.url), 'utf8');
const html = readFileSync(new URL('../../static/canvas.html', import.meta.url), 'utf8');
const css = readFileSync(new URL('../../static/css/canvas.css', import.meta.url), 'utf8');

assert.match(html, /id="controllerPanel"\s+class="controller-panel"/, 'canvas should include floating controller panel container');
assert.doesNotMatch(html, /id="globalMarkerToggle"/, 'top toolbar should not include the global marker entry');
assert.match(html, /data-image-edit-mode="marker"/, 'image detail marker mode should remain available');
assert.match(js, /function openControllerPanelForNode\(/, 'controller should expose floating panel opener');
assert.match(js, /function renderControllerPanel\(/, 'controller should render floating parameter panel');
assert.match(js, /function bindControllerPanel\(/, 'controller floating panel should bind parameter controls');
assert.match(js, /function materialHueToDisplayHue\(/, 'controller material HSL preview should include hue display helper');
assert.match(js, /function (fitControllerPanelToViewport|applyControllerPanelViewportFit)\(/, 'controller floating panel should adapt to viewport density');
assert.match(js, /function bindAngleCubeDrag\(/, 'controller angle panel should support cube drag interaction');
assert.match(js, /function (bindLightDirectionDrag|bindLightDotDrag|bindLightKnobDrag)\(/, 'controller lighting panel should support direction drag interaction');
assert.match(js, /function controllerWheelDirection\(/, 'controller panel should centralize wheel direction mapping');
assert.match(js, /return Number\(event\?\.deltaY \|\| 0\) > 0 \? 1 : -1;/, 'controller wheel direction should map scroll down to the next option');
assert.match(js, /const CONTROLLER_WHEEL_CYCLE_ZONES = new Set\(\[[\s\S]*'body'[\s\S]*'category'[\s\S]*'focal'[\s\S]*'vibe'[\s\S]*'shot'[\s\S]*'aperture'[\s\S]*'motion'[\s\S]*'angle-preset'[\s\S]*'subject-group'[\s\S]*'light-type'[\s\S]*'light-direction'[\s\S]*\]\);/, 'controller wheel cycling should be limited to camera, angle, and lighting zones');
assert.doesNotMatch(js, /CONTROLLER_WHEEL_CYCLE_ZONES[\s\S]*'material-/, 'material controller zones must not participate in wheel option cycling');
assert.match(js, /controllerPanel\.onwheel = e => \{/, 'controller panel wheel handler should be overwritten on render instead of accumulating listeners');
assert.doesNotMatch(js, /controllerPanel\.addEventListener\('wheel'/, 'controller panel should not add stacked wheel listeners on every render');
assert.match(js, /class="controller-open-panel"/, 'controller node should include floating-window button');
assert.match(js, /data-controller-collapse/, 'floating panel should support collapse');
assert.match(js, /function handleControllerPanelOutsidePointer\(event\)\{[\s\S]*controllerPanel\.classList\.contains\('open'\)[\s\S]*Date\.now\(\) < controllerPanelIgnoreOutsideUntil[\s\S]*isControllerPanelSafeTarget\(event\.target\)[\s\S]*closeControllerPanel\(\);[\s\S]*document\.addEventListener\('pointerdown', handleControllerPanelOutsidePointer, true\);/, 'clicking outside the controller floating panel should close it');
assert.match(js, /if\(!label \|\| !CANVAS_GENERATOR_TYPES\.includes\(node\.type\)\) return;/, 'controller effect badge should appear only on generator nodes, not output nodes');
assert.match(js, /function visiblePromptInputsForNode\(sources=\[\]\)\{[\s\S]*src\.type !== 'controller'/, 'controller directives should be hidden from prompt preview UI');
assert.doesNotMatch(js, /renderPromptPreview\([^\n]+sources\.filter\(src => src\.prompt && !src\.refs\?\.length\)/, 'prompt preview refresh should use controller-aware filtering');
assert.match(js, /function render\(\)[\s\S]*refreshOutputTimer\(\);\s*refreshControllerEffectBadges\(\);/, 'full render should restore controller effect badges');
assert.match(js, /function refreshNodes\(ids=\[\]\)[\s\S]*refreshOutputTimer\(\);\s*refreshControllerEffectBadges\(\);/, 'partial node refresh should restore controller effect badges');
assert.match(css, /\.controller-panel\.open/, 'controller panel open style should exist');
assert.match(css, /\.controller-panel\.collapsed/, 'controller panel collapsed style should exist');
assert.match(css, /\.controller-panel-tabs/, 'controller panel tab style should exist');
assert.match(css, /\.light-3d-stage/, 'controller lighting panel should include the full 3D lighting preview styles');
assert.match(css, /\.material-hsl-panel/, 'controller material panel should include HSL adjustment styles');
assert.match(css, /\.controller-panel\.fit-dense/, 'controller panel should include dense viewport fit styles');
assert.match(css, /\.ctrl-slider\.temperature-slider \.ctrl-slider-fill\s*\{[^}]*linear-gradient\(90deg,\s*#ff8a3d 0%,\s*#ffd08a 34%,\s*#fff3cf 50%,\s*#d7ecff 72%,\s*#8fbfff 100%\)[^}]*clip-path:inset\(0 calc\(100% - var\(--slider-fill,\s*0%\)\) 0 0\)/s, 'temperature slider fill should show a warm-to-cool gradient clipped by the real Kelvin position');
assert.match(js, /style="--slider-fill:\$\{\(fill\*100\)\.toFixed\(2\)\}%;"/, 'controller slider should expose the initial fill percentage as a CSS variable');
assert.match(js, /slider\.style\.setProperty\('--slider-fill',\s*\(fill\*100\)\.toFixed\(2\)\s*\+\s*'%'\);/, 'controller slider should keep the fill CSS variable synced while dragging');
assert.match(css, /\.theme-dark \.prompt-rich-input,/, 'rich prompt editor should inherit dark mode input styling');
assert.match(css, /\.theme-dark \.prompt-rich-input:empty::before/, 'rich prompt placeholder should be readable in dark mode');
assert.match(css, /\.node\.controller-node\s+\.controller-tabs\s*\{[^}]*grid-template-columns:\s*repeat\(2,\s*minmax\(0,\s*1fr\)\)/s, 'controller node switch panel should keep a stable two-column grid');
assert.match(css, /\.node\.controller-node\s*\{[^}]*width:\s*300px[^}]*max-width:\s*300px/s, 'controller node switch panel should stay narrow');
assert.match(js, /type:'controller'[^}]*w:300/, 'new controller nodes should use the narrow default width');
assert.match(css, /\.node\.controller-node\s+\.controller-tab\s*\{[^}]*grid-template-columns:\s*minmax\(0,1fr\)\s+36px/s, 'controller node tabs should reserve a fixed switch column');
assert.match(css, /\.node\.controller-node\s+\.controller-tab-label\s*\{[^}]*font-size:\s*12px[^}]*line-height:\s*1/s, 'controller node tab labels should use compact stable typography');
assert.match(css, /\.node\.controller-node\s+\.controller-tab-state\s*\{[^}]*font-size:\s*9px[^}]*line-height:\s*1/s, 'controller node tab state text should use compact stable typography');
assert.match(css, /\.node\.controller-node\s+\.controller-tab-switch\s*\{[^}]*width:\s*34px[^}]*height:\s*20px/s, 'controller node switch should stay compact');

console.log('controller floating panel tests passed');
