import assert from 'node:assert/strict';
import { readFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';

const root = resolve(process.cwd());
const main = readFileSync(resolve(root, 'main.py'), 'utf8');
const index = readFileSync(resolve(root, 'static/index.html'), 'utf8');
const apiSettings = readFileSync(resolve(root, 'static/js/api-settings.js'), 'utf8');
const canvasI18n = readFileSync(resolve(root, 'static/js/i18n/canvas.js'), 'utf8');

assert.match(main, /from hstar_runtime\.bootstrap import [^\n]*BootstrapStore/, 'backend must use the shared bootstrap store');
assert.match(main, /from hstar_runtime\.credentials import [\s\S]*create_credential_store/, 'backend must use the shared credential store');
assert.match(main, /from hstar_runtime\.api_merge import [^\n]*merge_api_defaults/, 'backend must understand packaged API defaults');
assert.match(main, /from hstar_runtime\.atomic import [^\n]*atomic_write_bytes/, 'backend configuration writes must be atomic');
assert.match(main, /from hstar_runtime\.paths import [^\n]*build_runtime_paths[^\n]*build_storage_path_map[^\n]*default_data_root[^\n]*uses_existing_legacy_storage_layout/, 'backend must use the typed runtime path builder, shared default root, and legacy-layout compatibility resolver');
assert.match(main, /os\.environ\.get\("HSTAR_PROGRAM_DIR"\)/, 'backend must accept the packaged program root');
assert.match(main, /os\.environ\.get\("HSTAR_DATA_DIR"[^)]*\)/, 'backend must accept the selected data root');
assert.match(main, /os\.environ\.get\("HSTAR_EDITION"/, 'backend must isolate edition bootstrap state');
assert.match(main, /elif EDITION == "development":\s*DATA_ROOT = default_data_root\(\)\.resolve\(\)/, 'development fallback must read the shared Hstar cache instead of AppData');
assert.match(main, /PRESERVE_EXISTING_DATA_ON_STARTUP\s*=\s*uses_existing_legacy_storage_layout\(RUNTIME_PATHS\)/, 'startup must keep legacy compatibility active after modern records are created');
assert.match(main, /MODERN_STORAGE_ACTIVE_ON_STARTUP\s*=\s*not PRESERVE_EXISTING_DATA_ON_STARTUP\s*or any\(/, 'modern maintenance must reactivate once modern storage exists beside legacy data');
assert.match(main, /INITIAL_STORAGE_PATHS\s*=\s*build_storage_path_map\(RUNTIME_PATHS\)/, 'primary runtime paths must always use the modern protocol');
assert.match(main, /LEGACY_STORAGE_PATHS\s*=\s*\([\s\S]*build_storage_path_map\(RUNTIME_PATHS, prefer_existing_legacy=True\)/, 'legacy paths must remain an independent compatibility source');
assert.match(main, /def bootstrap_app_software_settings\(\)\s*->\s*None:\s*if PRESERVE_EXISTING_DATA_ON_STARTUP:\s*return/, 'legacy-cache direct read must not copy software settings from another runtime');
assert.match(main, /def bootstrap_legacy_api_env\(\)\s*->\s*None:\s*if EDITION\.startswith\("test"\) or PRESERVE_EXISTING_DATA_ON_STARTUP:\s*return/, 'legacy-cache direct read must not migrate plaintext API settings or create backups');
assert.match(main, /if not PRESERVE_EXISTING_DATA_ON_STARTUP:[\s\S]*migrate_asset_library_into_dirs[\s\S]*migrate_double_extension_uploads[\s\S]*migrate_mislabeled_image_extensions/, 'legacy-sensitive asset maintenance must stay disabled whenever legacy data is present');
assert.match(main, /if MODERN_STORAGE_ACTIVE_ON_STARTUP:\s*VOICE_ASSISTANT\.schedule_background_tasks\(\)/, 'voice maintenance must run for an active modern layout without touching a legacy-only cache');
assert.match(main, /if os\.path\.isdir\(CANVAS_DIR\):[\s\S]*reconcile_saved_openshop_projects/, 'startup reconciliation must be scoped to existing modern canvas storage');
assert.match(main, /PRIMARY_OPENSHOP_STORE\s*=\s*OpenShopProjectStore\([\s\S]*create_directories=MODERN_STORAGE_ACTIVE_ON_STARTUP[\s\S]*\)/, 'modern OpenShop directories must initialize only when the modern layout is active');
assert.match(main, /def ensure_runtime_config_files\(\):[\s\S]*if not MODERN_STORAGE_ACTIVE_ON_STARTUP:\s*return/, 'configuration directories must initialize for a modern layout beside legacy data');
assert.match(main, /LEGACY_OPENSHOP_STORE\s*=\s*\([\s\S]*migrate_legacy_projects=False[\s\S]*\)/, 'legacy OpenShop reads must not migrate old project files');
assert.match(main, /OPENSHOP_STORE\s*=\s*OpenShopStorageRouter\(/, 'OpenShop operations must route by owning canvas storage source');
assert.match(main, /StorageOverlayStaticFiles\(\[OUTPUT_DIR, LEGACY_OUTPUT_DIR\]\)/, 'output delivery must resolve modern files before legacy files');
assert.match(main, /StorageOverlayStaticFiles\(\[ASSETS_DIR\]\)/, 'missing asset storage must return 404 without creating a directory');
assert.match(main, /def list_projects\(\):\s*projects = ensure_default_project\(persist=not PRESERVE_EXISTING_DATA_ON_STARTUP\)/, 'listing legacy-cache projects must not create or rewrite project data');
assert.match(main, /def cleanup_expired_canvas_trash\(\):\s*if not os\.path\.isdir\(CANVAS_DIR\):\s*return/, 'trash cleanup must ignore a legacy-only cache with no modern canvas directory');
assert.match(main, /def iter_canvas_records\(include_deleted=False\):\s*cleanup_expired_canvas_trash\(\)/, 'modern trash maintenance must remain active beside legacy canvases');
assert.doesNotMatch(main, /resolve_runtime_paths\(BASE_DIR,/, 'backend must not derive writable paths from the program directory');
assert.match(main, /LEGACY_API_ENV_FILE\s*=\s*os\.path\.join\(BASE_DIR,\s*"API",\s*"\.env"\)/, 'legacy API env may remain only as a migration source');
assert.match(main, /CREDENTIAL_FILE\s*=\s*RUNTIME_PATHS\.secrets_dir\s*\/\s*"credentials\.dpapi"/, 'credential storage must live beneath the selected data root');
assert.match(main, /CREDENTIAL_STORE\s*=\s*create_credential_store\(/, 'backend must initialize a credential backend');
assert.match(main, /CREDENTIAL_STORE\.update\(normalized_updates\)/, 'credential updates must use encrypted storage');
assert.doesNotMatch(main, /API_ENV_FILE\s*=\s*str\(/, 'backend must not define a writable plaintext API environment file');
assert.doesNotMatch(main, /with open\(API_ENV_FILE/, 'backend must not read or write a plaintext credential file directly');
assert.match(main, /PACKAGED_API_DEFAULTS_FILE\s*=\s*RUNTIME_PATHS\.api_defaults_dir\s*\/\s*"api-providers\.json"/, 'packaged API defaults must remain program-owned and read-only');
assert.match(main, /def load_packaged_api_defaults\(\):[\s\S]*merge_api_defaults\(\[\], document\)/, 'first-run defaults must be validated without user credential fields');
assert.match(main, /def save_api_providers\(providers\):[\s\S]*safe_providers\s*=\s*merge_api_defaults\(providers,\s*\[\]\)/, 'runtime provider saves must strip misplaced credential fields');
assert.match(main, /atomic_write_bytes\(Path\(API_PROVIDERS_FILE\), payload\)/, 'user API provider saves must use atomic replacement');
assert.doesNotMatch(apiSettings, /API\/\.env/, 'API settings must not tell users that credentials are stored in plaintext');
assert.doesNotMatch(canvasI18n, /API\/\.env/, 'canvas API help must describe encrypted credential storage');
assert.match(main, /USER_WORKFLOW_DIR\s*=\s*str\(RUNTIME_PATHS\.user_workflow_dir\)/, 'user workflows must have a writable data-root directory');
assert.match(main, /class SoftwareStorageRequest\(BaseModel\):/, 'storage save request model must exist');
assert.match(main, /class StorageMigrationRequest\(BaseModel\):/, 'asynchronous storage migration request model must exist');
assert.match(main, /@app\.get\("\/api\/software-settings"\)/, 'software settings read endpoint must exist');
assert.match(main, /@app\.post\("\/api\/software-settings\/storage"\)/, 'software storage save endpoint must exist');
assert.match(main, /@app\.post\("\/api\/storage-migrations",\s*status_code=202\)/, 'non-blocking storage migration endpoint must exist');
assert.match(main, /status_code=410/, 'legacy synchronous storage endpoint must direct callers to migration tasks');
assert.match(main, /@app\.get\("\/api\/collaboration-link"\)/, 'collaboration link endpoint must exist');
assert.match(main, /@app\.post\("\/api\/collaboration-link\/refresh"\)/, 'collaboration link refresh endpoint must exist');
assert.match(main, /purpose\s*==\s*"storage"/, 'native choose-folder must support storage purpose without breaking output save purpose');

const launcher = readFileSync(resolve(root, 'run.bat'), 'utf8');
assert.match(launcher, /set "HSTAR_EDITION=development"/, 'engineering launcher must set the development edition');
assert.match(launcher, /if not defined HSTAR_DATA_DIR \(/, 'engineering launcher must preserve an explicitly selected data root');
assert.match(launcher, /if exist "E:\\" \([\s\S]*set "HSTAR_DATA_DIR=E:\\Hstar缓存"/, 'engineering launcher must prefer the shared E-drive Hstar cache');
assert.match(launcher, /set "HSTAR_DATA_DIR=%USERPROFILE%\\Documents\\Hstar缓存"/, 'engineering launcher must retain the shared Documents fallback when E drive is unavailable');
assert.doesNotMatch(launcher, /set "HSTAR_DATA_DIR=%~dp0"/, 'engineering launcher must not store user data inside the source tree');
assert.match(launcher, /set "HSTAR_PROGRAM_DIR=%~dp0"/, 'engineering launcher must explicitly own its program root');
assert.match(launcher, /set "HSTAR_PORT=3000"/, 'engineering launcher must stay on port 3000');

assert.ok(existsSync(resolve(root, 'static/software-settings.html')), 'software settings page must exist');
assert.ok(existsSync(resolve(root, 'static/js/voice-settings-panel.js')), 'software settings must include the voice settings controller');
const settingsHtml = readFileSync(resolve(root, 'static/software-settings.html'), 'utf8');
assert.match(settingsHtml, /src="\/static\/js\/voice-settings-panel\.js\?v=[0-9.]+"/, 'software settings must load a versioned voice settings controller');
assert.match(index, /switchUI\(this, 'software-settings'\)/, 'sidebar must expose software settings entry');
assert.match(index, /id="frame-software-settings"/, 'stage must mount software settings iframe');
assert.match(index, /PAGE_IDS = \[[^\]]*'software-settings'/, 'software settings must be routable via PAGE_IDS');

console.log('software settings integration checks passed');
